// Code generated by counterfeiter. DO NOT EDIT.
package authfakes

import (
	"sync"

	"github.com/alphagov/paas-billing/apiserver/auth"
)

type FakeAuthorizer struct {
	AdminStub        func() (bool, error)
	adminMutex       sync.RWMutex
	adminArgsForCall []struct {
	}
	adminReturns struct {
		result1 bool
		result2 error
	}
	adminReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	HasBillingAccessStub        func([]string) (bool, error)
	hasBillingAccessMutex       sync.RWMutex
	hasBillingAccessArgsForCall []struct {
		arg1 []string
	}
	hasBillingAccessReturns struct {
		result1 bool
		result2 error
	}
	hasBillingAccessReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthorizer) Admin() (bool, error) {
	fake.adminMutex.Lock()
	ret, specificReturn := fake.adminReturnsOnCall[len(fake.adminArgsForCall)]
	fake.adminArgsForCall = append(fake.adminArgsForCall, struct {
	}{})
	stub := fake.AdminStub
	fakeReturns := fake.adminReturns
	fake.recordInvocation("Admin", []interface{}{})
	fake.adminMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthorizer) AdminCallCount() int {
	fake.adminMutex.RLock()
	defer fake.adminMutex.RUnlock()
	return len(fake.adminArgsForCall)
}

func (fake *FakeAuthorizer) AdminCalls(stub func() (bool, error)) {
	fake.adminMutex.Lock()
	defer fake.adminMutex.Unlock()
	fake.AdminStub = stub
}

func (fake *FakeAuthorizer) AdminReturns(result1 bool, result2 error) {
	fake.adminMutex.Lock()
	defer fake.adminMutex.Unlock()
	fake.AdminStub = nil
	fake.adminReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthorizer) AdminReturnsOnCall(i int, result1 bool, result2 error) {
	fake.adminMutex.Lock()
	defer fake.adminMutex.Unlock()
	fake.AdminStub = nil
	if fake.adminReturnsOnCall == nil {
		fake.adminReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.adminReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthorizer) HasBillingAccess(arg1 []string) (bool, error) {
	var arg1Copy []string
	if arg1 != nil {
		arg1Copy = make([]string, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.hasBillingAccessMutex.Lock()
	ret, specificReturn := fake.hasBillingAccessReturnsOnCall[len(fake.hasBillingAccessArgsForCall)]
	fake.hasBillingAccessArgsForCall = append(fake.hasBillingAccessArgsForCall, struct {
		arg1 []string
	}{arg1Copy})
	stub := fake.HasBillingAccessStub
	fakeReturns := fake.hasBillingAccessReturns
	fake.recordInvocation("HasBillingAccess", []interface{}{arg1Copy})
	fake.hasBillingAccessMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthorizer) HasBillingAccessCallCount() int {
	fake.hasBillingAccessMutex.RLock()
	defer fake.hasBillingAccessMutex.RUnlock()
	return len(fake.hasBillingAccessArgsForCall)
}

func (fake *FakeAuthorizer) HasBillingAccessCalls(stub func([]string) (bool, error)) {
	fake.hasBillingAccessMutex.Lock()
	defer fake.hasBillingAccessMutex.Unlock()
	fake.HasBillingAccessStub = stub
}

func (fake *FakeAuthorizer) HasBillingAccessArgsForCall(i int) []string {
	fake.hasBillingAccessMutex.RLock()
	defer fake.hasBillingAccessMutex.RUnlock()
	argsForCall := fake.hasBillingAccessArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthorizer) HasBillingAccessReturns(result1 bool, result2 error) {
	fake.hasBillingAccessMutex.Lock()
	defer fake.hasBillingAccessMutex.Unlock()
	fake.HasBillingAccessStub = nil
	fake.hasBillingAccessReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthorizer) HasBillingAccessReturnsOnCall(i int, result1 bool, result2 error) {
	fake.hasBillingAccessMutex.Lock()
	defer fake.hasBillingAccessMutex.Unlock()
	fake.HasBillingAccessStub = nil
	if fake.hasBillingAccessReturnsOnCall == nil {
		fake.hasBillingAccessReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.hasBillingAccessReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthorizer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.adminMutex.RLock()
	defer fake.adminMutex.RUnlock()
	fake.hasBillingAccessMutex.RLock()
	defer fake.hasBillingAccessMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthorizer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.Authorizer = new(FakeAuthorizer)
