dist: bionic
sudo: false

language: go

go:
  - 1.13

addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart

install:
  # Prevent default install task that does a `go get -t ./...`
  - true
  - GO111MODULE=off go get github.com/onsi/ginkgo/ginkgo
  - GO111MODULE=off go get github.com/maxbrunsfeld/counterfeiter

script:
  - export APP_ROOT="$TRAVIS_BUILD_DIR"
  - make test
