// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alphagov/paas-billing/cloudfoundry (interfaces: Client,UsageEventsAPI)

package mocks

import (
	cloudfoundry "github.com/alphagov/paas-billing/cloudfoundry"
	go_cfclient "github.com/alphagov/paas-billing/vendor/github.com/cloudfoundry-community/go-cfclient"
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
	time "time"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockClient) EXPECT() *MockClientMockRecorder {
	return _m.recorder
}

// Get mocks base method
func (_m *MockClient) Get(_param0 string) (*http.Response, error) {
	ret := _m.ctrl.Call(_m, "Get", _param0)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (_mr *MockClientMockRecorder) Get(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), arg0)
}

// GetApps mocks base method
func (_m *MockClient) GetApps() (map[string]go_cfclient.App, error) {
	ret := _m.ctrl.Call(_m, "GetApps")
	ret0, _ := ret[0].(map[string]go_cfclient.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApps indicates an expected call of GetApps
func (_mr *MockClientMockRecorder) GetApps() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetApps", reflect.TypeOf((*MockClient)(nil).GetApps))
}

// GetOrgs mocks base method
func (_m *MockClient) GetOrgs() (map[string]go_cfclient.Org, error) {
	ret := _m.ctrl.Call(_m, "GetOrgs")
	ret0, _ := ret[0].(map[string]go_cfclient.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrgs indicates an expected call of GetOrgs
func (_mr *MockClientMockRecorder) GetOrgs() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetOrgs", reflect.TypeOf((*MockClient)(nil).GetOrgs))
}

// GetServiceInstances mocks base method
func (_m *MockClient) GetServiceInstances() (map[string]go_cfclient.ServiceInstance, error) {
	ret := _m.ctrl.Call(_m, "GetServiceInstances")
	ret0, _ := ret[0].(map[string]go_cfclient.ServiceInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceInstances indicates an expected call of GetServiceInstances
func (_mr *MockClientMockRecorder) GetServiceInstances() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetServiceInstances", reflect.TypeOf((*MockClient)(nil).GetServiceInstances))
}

// GetServicePlans mocks base method
func (_m *MockClient) GetServicePlans() (map[string]go_cfclient.ServicePlan, error) {
	ret := _m.ctrl.Call(_m, "GetServicePlans")
	ret0, _ := ret[0].(map[string]go_cfclient.ServicePlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServicePlans indicates an expected call of GetServicePlans
func (_mr *MockClientMockRecorder) GetServicePlans() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetServicePlans", reflect.TypeOf((*MockClient)(nil).GetServicePlans))
}

// GetServices mocks base method
func (_m *MockClient) GetServices() (map[string]go_cfclient.Service, error) {
	ret := _m.ctrl.Call(_m, "GetServices")
	ret0, _ := ret[0].(map[string]go_cfclient.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServices indicates an expected call of GetServices
func (_mr *MockClientMockRecorder) GetServices() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetServices", reflect.TypeOf((*MockClient)(nil).GetServices))
}

// GetSpaces mocks base method
func (_m *MockClient) GetSpaces() (map[string]go_cfclient.Space, error) {
	ret := _m.ctrl.Call(_m, "GetSpaces")
	ret0, _ := ret[0].(map[string]go_cfclient.Space)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpaces indicates an expected call of GetSpaces
func (_mr *MockClientMockRecorder) GetSpaces() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetSpaces", reflect.TypeOf((*MockClient)(nil).GetSpaces))
}

// MockUsageEventsAPI is a mock of UsageEventsAPI interface
type MockUsageEventsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockUsageEventsAPIMockRecorder
}

// MockUsageEventsAPIMockRecorder is the mock recorder for MockUsageEventsAPI
type MockUsageEventsAPIMockRecorder struct {
	mock *MockUsageEventsAPI
}

// NewMockUsageEventsAPI creates a new mock instance
func NewMockUsageEventsAPI(ctrl *gomock.Controller) *MockUsageEventsAPI {
	mock := &MockUsageEventsAPI{ctrl: ctrl}
	mock.recorder = &MockUsageEventsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockUsageEventsAPI) EXPECT() *MockUsageEventsAPIMockRecorder {
	return _m.recorder
}

// Get mocks base method
func (_m *MockUsageEventsAPI) Get(_param0 string, _param1 int, _param2 time.Duration) (*cloudfoundry.UsageEventList, error) {
	ret := _m.ctrl.Call(_m, "Get", _param0, _param1, _param2)
	ret0, _ := ret[0].(*cloudfoundry.UsageEventList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (_mr *MockUsageEventsAPIMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Get", reflect.TypeOf((*MockUsageEventsAPI)(nil).Get), arg0, arg1, arg2)
}

// Type mocks base method
func (_m *MockUsageEventsAPI) Type() string {
	ret := _m.ctrl.Call(_m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type
func (_mr *MockUsageEventsAPIMockRecorder) Type() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Type", reflect.TypeOf((*MockUsageEventsAPI)(nil).Type))
}
