// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/alphagov/paas-billing/eventserver/auth"
)

type FakeAuthorizer struct {
	AdminStub        func() (bool, error)
	adminMutex       sync.RWMutex
	adminArgsForCall []struct{}
	adminReturns     struct {
		result1 bool
		result2 error
	}
	adminReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	OrganisationsStub        func([]string) (bool, error)
	organisationsMutex       sync.RWMutex
	organisationsArgsForCall []struct {
		arg1 []string
	}
	organisationsReturns struct {
		result1 bool
		result2 error
	}
	organisationsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthorizer) Admin() (bool, error) {
	fake.adminMutex.Lock()
	ret, specificReturn := fake.adminReturnsOnCall[len(fake.adminArgsForCall)]
	fake.adminArgsForCall = append(fake.adminArgsForCall, struct{}{})
	fake.recordInvocation("Admin", []interface{}{})
	fake.adminMutex.Unlock()
	if fake.AdminStub != nil {
		return fake.AdminStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.adminReturns.result1, fake.adminReturns.result2
}

func (fake *FakeAuthorizer) AdminCallCount() int {
	fake.adminMutex.RLock()
	defer fake.adminMutex.RUnlock()
	return len(fake.adminArgsForCall)
}

func (fake *FakeAuthorizer) AdminReturns(result1 bool, result2 error) {
	fake.AdminStub = nil
	fake.adminReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthorizer) AdminReturnsOnCall(i int, result1 bool, result2 error) {
	fake.AdminStub = nil
	if fake.adminReturnsOnCall == nil {
		fake.adminReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.adminReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthorizer) Organisations(arg1 []string) (bool, error) {
	var arg1Copy []string
	if arg1 != nil {
		arg1Copy = make([]string, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.organisationsMutex.Lock()
	ret, specificReturn := fake.organisationsReturnsOnCall[len(fake.organisationsArgsForCall)]
	fake.organisationsArgsForCall = append(fake.organisationsArgsForCall, struct {
		arg1 []string
	}{arg1Copy})
	fake.recordInvocation("Organisations", []interface{}{arg1Copy})
	fake.organisationsMutex.Unlock()
	if fake.OrganisationsStub != nil {
		return fake.OrganisationsStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.organisationsReturns.result1, fake.organisationsReturns.result2
}

func (fake *FakeAuthorizer) OrganisationsCallCount() int {
	fake.organisationsMutex.RLock()
	defer fake.organisationsMutex.RUnlock()
	return len(fake.organisationsArgsForCall)
}

func (fake *FakeAuthorizer) OrganisationsArgsForCall(i int) []string {
	fake.organisationsMutex.RLock()
	defer fake.organisationsMutex.RUnlock()
	return fake.organisationsArgsForCall[i].arg1
}

func (fake *FakeAuthorizer) OrganisationsReturns(result1 bool, result2 error) {
	fake.OrganisationsStub = nil
	fake.organisationsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthorizer) OrganisationsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.OrganisationsStub = nil
	if fake.organisationsReturnsOnCall == nil {
		fake.organisationsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.organisationsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthorizer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.adminMutex.RLock()
	defer fake.adminMutex.RUnlock()
	fake.organisationsMutex.RLock()
	defer fake.organisationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthorizer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.Authorizer = new(FakeAuthorizer)
