CREATE OR REPLACE FUNCTION max_time(
  a TIMESTAMPTZ,
  b TIMESTAMPTZ
) RETURNS TIMESTAMPTZ LANGUAGE plpgsql AS $$
BEGIN
  IF a > b THEN
    RETURN a;
  ELSE
    RETURN b;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION min_time(
  a TIMESTAMPTZ,
  b TIMESTAMPTZ
) RETURNS TIMESTAMPTZ LANGUAGE plpgsql AS $$
BEGIN
  IF a > b THEN
    RETURN a;
  ELSE
    RETURN b;
  END IF;
END $$;
