on:
  - pull_request

env:
  GO_VERSION: "1.20"

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests

    ## Setup
    services:
      postgres:
        image: postgres:12.5
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: test
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name test-postgres
        ports:
          - 5432:5432
    steps:
      - name: Increase postgres max_connections
        run: |
          docker exec -i test-postgres bash << EOF
            sed -i -e 's/^max_connections = .*/max_connections = 500/' /var/lib/postgresql/data/postgresql.conf
          EOF
          docker restart --time 0 test-postgres
          sleep 5

      - name: Checkout repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: "Install Go ${{env.GO_VERSION}}"
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: "${{env.GO_VERSION}}"

      ## Tests
      - name: "make test"
        env:
          TMPDIR: "${{runner.temp}}"
          GOPATH: "/home/runner/go"
          GOBIN: "/home/runner/go/bin"
          TEST_DATABASE_URL: postgresql://postgres:secret@localhost:5432/test?sslmode=disable
        run: |
          make test
